name: 'Build & Deploy Production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - name: Run Build Production (create dist folder)
        run: npm run build


