name: 'Build & Deploy Production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - name: Run Build Production (create dist folder)
        run: npm run build
      - name: Upload dist folder artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist

  deploy-to-production:
    needs: build-production-job
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-production
          path: dist

      - run: ls dist

      - uses: actions/checkout@v4
      - name: publish vue to github page
        uses: SerhiiKa/VuePagesAction@1.0.4
        with:
          username: ${{github.actor}}
          reponame: ${{github.event.repository.name}}
          token: ${{secrets.GITHUB_TOKEN}}
