name: "CI"

on:
  push:
    branches:
      - main

# defaults:
#   run:
#     working-directory: './app'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set nodejs version to 20.x
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'

        - run: npm ci
       

        - name: Run Lint
          run: npm run lint
        
